### ISSUE TITLE
TemplateSyntaxError: No named cycles in template. 'row1,row2' is not defined

### ISSUE THREAD

**Issue by erasmodanarni** [adandan01/mybook#1]
Hello! Thanks for you tutorial. Unfortunately I couldn't have it running... I get the following error:

`TemplateSyntaxError: No named cycles in template. 'row1,row2' is not defined`

In the "myprofile" template.

**Comment by adandan01** [comment]
Hi @erasmodanarni Thank you for reporting this. I have updated the template. It was written in django 1.9. The syntax for cycle is slightly different now.
